language: node_js
dist: trusty
node_js:
  - "8.11.1"
addons:
  chrome: stable
before_script:
  - npm link
script: npm test
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
